name: Trigger auto deployment for eshoponweb-dp-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/eshoponweb-dp-container-AutoDeployTrigger-80179f5d-1297-42cd-a67b-996d83535429.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ESHOPONWEBDPCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ESHOPONWEBDPCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ESHOPONWEBDPCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrydp.azurecr.io
          registryUsername: ${{ secrets.ESHOPONWEBDPCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ESHOPONWEBDPCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: eshoponweb-dp-container
          resourceGroup: Learn
          imageToBuild: containerregistrydp.azurecr.io/eshoponweb-dp-container:${{ github.sha }}
          dockerfilePath: Dockerfile


