name: Build and deploy .NET application to container app public-api-dp-container
on:
  push:
    branches:
    - develop
env:
  CONTAINER_APP_CONTAINER_NAME: web
  CONTAINER_APP_NAME: public-api-dp-container
  CONTAINER_APP_RESOURCE_GROUP_NAME: Learn
  CONTAINER_REGISTRY_LOGIN_SERVER: azurecontainerregisterdp.azurecr.io
  DOCKER_FILE_PATH: src/PublicApi/Dockerfile
  PROJECT_NAME_FOR_DOCKER: publicapi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.azurecontainerregisterdp_USERNAME_F68A }}
        password: ${{ secrets.azurecontainerregisterdp_PASSWORD_F68A }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.public_api_dp_container_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.azurecontainerregisterdp_USERNAME_F68A }} --password ${{ secrets.azurecontainerregisterdp_PASSWORD_F68A }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
